title: Marc Aube
description: Software craftsmanship, rants and randomness

exclude: [README.md]

url: http://marcaube.ca
baseurl: ""
paginate_path: "/page/page:num/"
permalink: /:categories/:year/:month/:title

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: Articles
      url: /articles.html
    - title: My bookshelf
      url: /books.html
# - title: About
#   url: /about
# - title: Contact
#   url: /contact

social:
   github: marcaube
   twitter: maaube
   disqus: marcaube

github:
    repository_url: https://github.com/marcaube/marcaube.github.io

google_analytics: "UA-24040542-3"
